[providers]
node = "18"
python = "3.11"

[phases.install]
cmds = [
  "cd frontend && yarn install",
  "cd backend && pip install -r requirements.txt"
]

[phases.build]
cmds = ["cd frontend && yarn build"]

[start]
cmd = "cd frontend && yarn start"