[phases.setup]
nixPkgs = ["nodejs", "yarn", "python310", "pip"]

[phases.install]
cmds = [
  "cd frontend && yarn install",
  "cd backend && pip install -r requirements.txt"
]

[phases.build]
cmds = ["cd frontend && yarn build"]

[start]
cmd = "cd frontend && yarn start"